// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.1
// source: AccountStatusEnum.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountStatus int32

const (
	AccountStatus_ACTIVE_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACTIVE_STATUS_ACTIVE      AccountStatus = 1
	AccountStatus_ACTIVE_STATUS_INACTIVE    AccountStatus = 2
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACTIVE_STATUS_UNSPECIFIED",
		1: "ACTIVE_STATUS_ACTIVE",
		2: "ACTIVE_STATUS_INACTIVE",
	}
	AccountStatus_value = map[string]int32{
		"ACTIVE_STATUS_UNSPECIFIED": 0,
		"ACTIVE_STATUS_ACTIVE":      1,
		"ACTIVE_STATUS_INACTIVE":    2,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_AccountStatusEnum_proto_enumTypes[0].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_AccountStatusEnum_proto_enumTypes[0]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_AccountStatusEnum_proto_rawDescGZIP(), []int{0}
}

type AccountStatusEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveStatusActive AccountStatus `protobuf:"varint,1,opt,name=active_status_active,json=activeStatusActive,proto3,enum=example.enumerations.AccountStatus" json:"active_status_active,omitempty"`
}

func (x *AccountStatusEnum) Reset() {
	*x = AccountStatusEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AccountStatusEnum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountStatusEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountStatusEnum) ProtoMessage() {}

func (x *AccountStatusEnum) ProtoReflect() protoreflect.Message {
	mi := &file_AccountStatusEnum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountStatusEnum.ProtoReflect.Descriptor instead.
func (*AccountStatusEnum) Descriptor() ([]byte, []int) {
	return file_AccountStatusEnum_proto_rawDescGZIP(), []int{0}
}

func (x *AccountStatusEnum) GetActiveStatusActive() AccountStatus {
	if x != nil {
		return x.ActiveStatusActive
	}
	return AccountStatus_ACTIVE_STATUS_UNSPECIFIED
}

var File_AccountStatusEnum_proto protoreflect.FileDescriptor

var file_AccountStatusEnum_proto_rawDesc = []byte{
	0x0a, 0x17, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45,
	0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x6a, 0x0a, 0x11, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x45, 0x6e, 0x75, 0x6d, 0x12, 0x55, 0x0a, 0x14, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x23, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x65, 0x6e, 0x75,
	0x6d, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x12, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x2a, 0x64, 0x0a, 0x0d, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x19,
	0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x41,
	0x43, 0x54, 0x49, 0x56, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x43, 0x54,
	0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10,
	0x02, 0x42, 0x0e, 0x5a, 0x0c, 0x65, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AccountStatusEnum_proto_rawDescOnce sync.Once
	file_AccountStatusEnum_proto_rawDescData = file_AccountStatusEnum_proto_rawDesc
)

func file_AccountStatusEnum_proto_rawDescGZIP() []byte {
	file_AccountStatusEnum_proto_rawDescOnce.Do(func() {
		file_AccountStatusEnum_proto_rawDescData = protoimpl.X.CompressGZIP(file_AccountStatusEnum_proto_rawDescData)
	})
	return file_AccountStatusEnum_proto_rawDescData
}

var file_AccountStatusEnum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_AccountStatusEnum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AccountStatusEnum_proto_goTypes = []interface{}{
	(AccountStatus)(0),        // 0: example.enumerations.AccountStatus
	(*AccountStatusEnum)(nil), // 1: example.enumerations.AccountStatusEnum
}
var file_AccountStatusEnum_proto_depIdxs = []int32{
	0, // 0: example.enumerations.AccountStatusEnum.active_status_active:type_name -> example.enumerations.AccountStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_AccountStatusEnum_proto_init() }
func file_AccountStatusEnum_proto_init() {
	if File_AccountStatusEnum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AccountStatusEnum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountStatusEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AccountStatusEnum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AccountStatusEnum_proto_goTypes,
		DependencyIndexes: file_AccountStatusEnum_proto_depIdxs,
		EnumInfos:         file_AccountStatusEnum_proto_enumTypes,
		MessageInfos:      file_AccountStatusEnum_proto_msgTypes,
	}.Build()
	File_AccountStatusEnum_proto = out.File
	file_AccountStatusEnum_proto_rawDesc = nil
	file_AccountStatusEnum_proto_goTypes = nil
	file_AccountStatusEnum_proto_depIdxs = nil
}
